os: unstable

branches:
  only:
    - master

shallow_clone: true
clone_depth: 1

skip_tags: true

environment:
  nodejs_version: "8"
# GH_TOKEN set via UI

cache:
  - node_modules -> package.json

# For 64 bit, we need:
# - ps: Install-Product node %env:nodejs_version x64
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install 7zip-bin-win # platform specific dependency of electron-builder

# We don't want to run 'msbuild' but do need to build prior to testing
build: off
before_test:
  - npm run build

test_script:
  - node --version
  - npm --version
  - npm test

after_test:
  - npm run dist
