build: off

os: unstable

branches:
  only:
    - master

shallow_clone: true
clone_depth: 1

skip_tags: true

environment:
  nodejs_version: "6"
# GH_TOKEN set via UI

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm
  - .\node_modules\.bin\npm install

test_script:
  - node --version
  - .\node_modules\.bin\npm --version
  - .\node_modules\.bin\npm test

after_test:
  - .\node_modules\.bin\npm run dist
