build: off

os: unstable

branches:
  only:
    - master

shallow_clone: true
clone_depth: 1

skip_tags: true

environment:
  nodejs_version: "6"
# GH_TOKEN set via UI

cache:
  - node_modules -> package.json

# For 64 bit, we need:
# - ps: Install-Product node %env:nodejs_version x64
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

after_test:
  - npm run dist
