branches:
  only:
    - master
    - /^greenkeeper/.*$/

dist: trusty
sudo: false

language: node_js
node_js:
  - "8"

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - rpm            # dist
      - xvfb           # testing
      - openjpeg-tools # electron-builder's icon dependency
      - snapd          # to, in turn, install snapcraft as a snap

install:
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then sudo snap install --classic snapcraft && source /etc/profile.d/apps-bin-path.sh && snap list && snapcraft --version; fi
  - npm install

cache:
  directories:
    - node_modules

before_script:
  - npm run build

script: # we want to be notified if any of these fail, so use script rather than after_success
  - npm test && DEBUG=electron-builder npm run dist # only dist if the tests pass
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then npm run coveralls; fi
