branches:
  only:
    - master

dist: trusty
sudo: false

language: node_js
node_js:
  - 6

os:
  - linux
  - osx

addons:
  # artefacts TODO
  apt:
    packages:
      - xvfb
      - icnsutils # this + gm are for electron-builder's icon work
      - graphicsmagick

cache:
  directories:
    - node_modules

after_success:
  - npm run dist
