dist: trusty
language: node_js

node_js:
  - 6

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - xvfb

branches:
  only:
    - master

cache:
  directories:
    - node_modules

after_success:
  - npm run dist
