branches:
  only:
    - master
    - /^greenkeeper/.*$/

dist: trusty
sudo: false

language: node_js
node_js:
  - 7

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - rpm       # dist
      - xvfb      # testing
      - icnsutils # this + gm for electron-builder's icon work
      - graphicsmagick

cache:
  directories:
    - node_modules

before_script:
  - npm run build

after_success:
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
      npm run coveralls;
    fi
  - npm run dist
