branches:
  only:
    - master
    - /^greenkeeper/.*$/

dist: trusty
sudo: false

language: node_js
node_js:
  - "8"

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - sourceline: 'ppa:snappy-dev/tools'
    packages:
      - rpm       # dist
      - xvfb      # testing
      - openjpeg-tools # this + gm for electron-builder's icon work
      - snapcraft # 14.04 doesn't come with this by default, and its not in the main repo

cache:
  directories:
    - node_modules

before_script:
  - npm run build

script: # we want to be notified if any of these fail, so use script rather than after_success
  - npm test && npm run dist # only dist if the tests pass
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then npm run coveralls; fi
